/**
 * Central UI Copy repository for Stowly.
 * All fixed UI wording, button text, headings, validation messages and static labels
 * live here to guarantee consistent natural English across the entire platform.
 */

export const COPY = {
  brand: {
    name: 'Stowly',
    tagline: 'Private Cloud Workspace & Zero-Knowledge Vault',
    supportEmail: 'support@stowly.internal',
    version: '2.1.0',
    liveBadge: 'Live Workspace',
  },
  nav: {
    home: 'Home Base',
    myStash: 'My Stash',
    justOpened: 'Just Opened',
    pinned: 'Pinned',
    smartShelves: 'Smart Shelves',
    dropBoxes: 'Drop Boxes',
    spacePulse: 'Space Pulse',
    recycleBin: 'Recycle Bin',
    keyring: 'Keyring',
    settings: 'Settings',
    notifications: 'Notifications',
    adminControl: 'Admin Control Room',
    userWorkspace: 'User Workspace',
    logOut: 'Log out',
    logOutConfirmTitle: 'Log out of Stowly?',
    logOutConfirmMsg: 'Your Keyring Vault is currently unlocked. Logging out will lock the vault and clear all decrypted keys from browser memory.',
  },
  storage: {
    label: 'Storage Meter',
    usedOfQuota: '{used} of {quota} used',
    freeSpace: '{free} free',
    freeUpSpace: 'Free up space',
    fullWarning: 'Storage limit reached (100%). New uploads blocked until space is freed.',
    highWarning: 'Storage warning ({percent}% used). Space running low.',
    exceedsQuota: 'Upload of {size} exceeds available storage quota by {extra}.',
  },
  notifications: {
    title: 'Notifications',
    markAllRead: 'Mark all as read',
    seeAllInSettings: 'See all in Settings',
    emptyTitle: "You're all caught up",
    emptyText: 'New system alerts and Drop Box delivery updates will appear here.',
    retry: 'Retry',
    loadMore: 'Load more notifications',
  },
  settings: {
    title: 'Settings',
    subtitle: 'Manage your profile, security, devices, notifications and preferences.',
    profile: {
      title: 'Profile Settings',
      subtitle: 'Manage your public workspace identity and details.',
      nameLabel: 'Full name',
      emailLabel: 'Email address',
      emailHint: 'Your email is read-only and used for account sign-in.',
      bioLabel: 'Bio',
      bioPlaceholder: 'Tell us a little about your role or workspace...',
      memberSince: 'Member since {date}',
      unsavedChanges: 'You have unsaved profile changes',
      save: 'Save changes',
      discard: 'Discard',
    },
    shield: {
      title: 'Shield & Security',
      subtitle: 'Manage your login credentials, password strength, and Keyring vault settings.',
      changePassword: 'Change Password',
      currentPassword: 'Current password',
      newPassword: 'New password',
      confirmPassword: 'Confirm new password',
      showPasswords: 'Show passwords',
      hidePasswords: 'Hide passwords',
      updatePasswordBtn: 'Update password',
      passwordRevokeNotice: 'Note: Updating your password revokes all active sessions on other devices for security.',
      vaultStatus: 'Vault Status',
      unlocked: 'Unlocked',
      locked: 'Locked',
      lockNow: 'Lock now',
      autoLockLabel: 'Inactivity Auto-Lock',
      autoLockDesc: 'Automatically locks vault after idle time.',
    },
    devices: {
      title: 'Active Devices',
      subtitle: 'Sessions currently signed into your Stowly account.',
      signOutAllOthers: 'Sign out all others',
      thisDevice: 'This device',
      activeTime: 'Active {time} · Created {created}',
      signOutBtn: 'Sign out',
      confirmTitle: 'Sign out other devices?',
      confirmMsg: 'Every active session except this device will be revoked immediately.',
    },
    alerts: {
      title: 'Alerts & Notifications',
      subtitle: 'Control notification preferences and view your recent activity feed.',
      preferencesHeader: 'Preferences',
      recentActivityHeader: 'Recent Activity',
      dropsPref: 'Drop Box deliveries',
      dropsDesc: 'Get notified when guest files arrive in your Drop Boxes.',
      accountPref: 'Account updates',
      accountDesc: 'Get notified about approval and administrative changes.',
      storagePref: 'Storage warnings',
      storageDesc: 'Get notified when disk usage reaches capacity limits.',
    },
    personalize: {
      title: 'Personalization',
      subtitle: 'Customize how files and workspace views are rendered.',
      defaultLayoutHeader: 'Default File Layout',
      defaultLayoutDesc: 'Choose the default view when opening My Stash or file collections.',
      gridView: 'Grid View',
      gridDesc: 'Card tiles with preview icons',
      listView: 'List View',
      listDesc: 'Compact tabular rows',
      densityHeader: 'Density & Display',
      compactDensity: 'Compact Density',
      compactDesc: 'Reduces padding and height across lists for high data density.',
    },
  },
  keyring: {
    title: 'Keyring Vault',
    subtitle: 'Zero-knowledge client-side encrypted password manager.',
    masterPassLabel: 'Master Password',
    unlockBtn: 'Unlock Keyring',
    lockBtn: 'Lock Vault',
    setupTitle: 'Initialize Keyring Vault',
    setupDesc: 'Create a master password. It never leaves your browser.',
  },
  admin: {
    title: 'Admin Control Room',
    subtitle: 'Approve accounts, manage user quotas, and review system audit logs.',
    statsTotal: 'Total Members',
    statsPending: 'Pending Approval',
    statsApproved: 'Approved Users',
    statsRejected: 'Rejected Users',
    approveBtn: 'Approve User',
    rejectBtn: 'Reject Request',
    suspendBtn: 'Suspend Account',
    reactivateBtn: 'Reactivate',
    quotaBtn: 'Change Quota',
  },
};
